### PR TITLE
Make people do npm version manually

### PR DESCRIPTION
**Pull request by rvdh**

### CODE REVIEW

**Comment by ChrisTerBeke** [comment]
I guess @matijs wants to have a look as it was flagged by him?

**Comment by ianpaschal** [comment]
Thanks @rvdh! I think this is a pretty good solution.

**Comment by rvdh** [comment]
> Would this require to push directly to master (the version number in package.json)? If so, that's gonna be a problem.

Dont think so, npm will just commit to whatever branch you're on. But that does mean you'll have to create a PR to merge the version update in package.json and the tag will point to a commit in a branch.

**Comment by ChrisTerBeke** [comment]
> > Would this require to push directly to master (the version number in package.json)? If so, that's gonna be a problem.
> 
> Dont think so, npm will just commit to whatever branch you're on. But that does mean you'll have to create a PR to merge the version update in package.json and the tag will point to a commit in a branch.

That's fine, that commit will end up in master after merging anyways.

**Comment by ChrisTerBeke** [comment]
Btw, also needed in stardust-web-components and that new eslint repo?

**Pull request merged**
