### PR TITLE
CS-139 Turn off autocomplete for all number input fields

### PR DESCRIPTION
**Pull request by sedwards2009**
CS-139

This turns autocomplete off for all number input fields.

It is not configurable.

### CODE REVIEW

**Comment by sedwards2009** [comment]
What I want is for the browser not to offer completions for number inputs (which are almost always wrong).

As for whether this should be configurable, I don't know but I also can't think of a use case that requires it.

**Comment by ChrisTerBeke** [comment]
@rvdh this PR is not picked up

**Comment by rvdh** [comment]
@ChrisTerBeke started it manually, but it fails.

**Comment by matijs** [comment]
@sedwards2009 any word on the bug?

**Comment by sedwards2009** [comment]
@matijs the jira issue is back in TODO and anyone who can reproduce the issue (I can't) is free to pick it up.

This one-liner PR can be deleted as far as I'm concerned.

**Comment by matijs** [comment]
Deleting this until the bug becomes current again.

**Pull request closed without merging**
