### PR TITLE
Replace node-sass with Dart sass

### PR DESCRIPTION
**Pull request by matijs**
- use sass instead of node-sass
- bring `.storybook/webpack.config.js` in line with code style

### CODE REVIEW

**Comment by ImreBognarUltimaker** [comment]
Why is it better?

**Comment by matijs** [comment]
I believe Dart Sass is now the reference implementation. It's also slightly stricter but most importantly, there are no requirements for platform specific binaries as it's all JS.

**Comment by matijs** [comment]
(I am also trying to speed up things a little. Having to wait ~3 minutes for Storybook to start is not really acceptable)

**Comment by ChrisTerBeke** [comment]
Always nice to see improvements :) I have no opinion on node-sass vs sass, so if the front-enders are happy with its let's do it.

**Comment by ChrisTerBeke** [comment]
Approved by multiple people, I'll just merge it I guess to not have lingering PRs.

**Pull request merged**
